### ISSUE TITLE
Problem in adding LMIC library

### ISSUE THREAD

**Issue by manisubbu07** [tftelkamp/arduino-lmic-v1.5#8]
hi 
i've downloaded Arduino-lmic-master.zip and try to add this to my arduino software by click sketch->importlibrary->select the file.
but i get the in arduino software as 
the library "arduino-lmic-master" cannot be used.the library file should contain only basic basic letters and numbers.
what can i do further

**Comment by gonzalocasas** [comment]
As it says in the home page of this repo:
```
**IMPORTANT**
Please note this repository is deprecated.
For LMiC 1.5 on Arduino please use:
https://github.com/matthijskooijman/arduino-lmic
```

so, please try the updated repo. I've been using it for a very long time without any issues, make sure your Arduino IDE is up-to-date as well.
